DECLARE
	CURSOR CUREMP IS 
	SELECT E.ENAME,E.HIREDATE,D.DNAME,D.LOC
	FROM EMP E, DEPT D
	WHERE E.DEPTNO=D.DEPTNOL;
BEGIN
	DBMS_OUTPUT.PUT_LINE('NAME' || 'HIREDATE' || 'DEPTNAME' || 'LOC');
	FOR I IN CUREMP
		DBMS_OUTPUT.PUT_LINE(I.ENAME || I.HIREDATE || I.DNAME|| I.LOC);
	END LOOP;
END;
/







