DECLARE
	VENAME EMP.ENAME%TYPE;
	VSAL EMP.SAL%TYPE;
	VGRADE SALGRADE.GRADE%TYPE;
BEGIN
	SELECT EMP.ENAME,EMP.SAL,SALGRADE.GRADE
	INTO VENAME,VSAL,VGRADE
	FROM EMP,SALGRADE
	WHERE EMP.SAL BETWEEN SALGRADE.LOSAL
	AND SALGRADE.HISAL
	AND EMP.EMPNO=&NO;
	
	DBMS_OUTPUT.PUT_LINE('======================');
	
	DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME:-'||VENAME);
	DBMS_OUTPUT.PUT_LINE('SAL:-'||VSAL);
	DBMS_OUTPUT.PUT_LINE('GRADE:-'||VGRADE);
END;
/