DECLARE
	VENAME EMP.ENAME%TYPE;
	VSAL EMP.SAL%TYPE;
BEGIN
	SELECT ENAME,SAL
	INTO VENAME,VSAL
	FROM EMP
	WHERE SAL=(SELECT MAX(SAL) FROM EMP);
	
	DBMS_OUTPUT.PUT_LINE('================================');
	
	DBMS_OUTPUT.PUT_LINE('HIGHEST PAID EMP NAME:-'||VENAME);
	DBMS_OUTPUT.PUT_LINE('SAL:-'||VSAL);
	
	DBMS_OUTPUT.PUT_LINE('================================');
END;
/