DECLARE
	VENAME EMP.ENAME%TYPE;
	VJOB EMP.JOB%TYPE;
	VDNAME DEPT.DNAME%TYPE;
	VLOC DEPT.LOC%TYPE;
BEGIN
	SELECT EMP.ENAME,EMP.JOB,DEPT.DNAME,DEPT.LOC
	INTO VENAME,VJOB,VDNAME,VLOC
	FROM EMP,DEPT
	WHERE EMP.DEPTNO=DEPT.DEPTNO 
	AND EMP.EMPNO=&NO;

	DBMS_OUTPUT.PUT_LINE('_____________________________');
	DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME'||VENAME);
	DBMS_OUTPUT.PUT_LINE('JOB:-'||VJOB);
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME:-'||VDNAME);
	DBMS_OUTPUT.PUT_LINE('LOC:-'||VLOC);
	DBMS_OUTPUT.PUT_LINE('_____________________________');
END;
/