DECLARE 
	CURSOR PARAEMP(N1 NUMBER) IS
	SELECT ENAME,JOB FROM EMP WHERE EMPNO=N1;
	VEMPROW PARAEMP%ROWTYPE;
BEGIN
	DBMS_OUTPUT.PUT_LINE('-----------------------------');
	N1:&NO;
	OPEN PARAEMP(&N1);
	FETCH PARAEMP INTO VEMPROW;
	DBMS_OUTPUT.PUT_LINE('-----------------------------');
	DBMS_OUTPUT.PUT_LINE(VEMPROW.ENAME || VEMPROW.JOB);
	CLOSE PARAEMP;
	DBMS_OUTPUT.PUT_LINE(VEMPROW.ENAME || VEMPROW.JOB);
END;
/