DECLARE

	EMPNO EMP.EMPNO%TYPE;
	NAME VARCHAR2(20);
	SAL NUMBER;
	DA NUMBER;
	HRA NUMBER;
	IT NUMBER;
	NETSAL NUMBER;
	
BEGIN
	DBMS_OUTPUT.PUT_LINE('=================');
	DBMS_OUTPUT.PUT_LINE('SALARY SLIP');
	DBMS_OUTPUT.PUT_LINE('=================');
	
	SELECT EMPNO, NAME, SAL, DA,
END;
/