CREATE TABLE STUDENT1(
	SNO NUMBER(3) CONSTRAINTS PKSID1 PRIMARY KEY,
	NAME VARCHAR2(15),
	COURSE VARCHAR2(10) DEFAULT 'BCA'
);

CREATE TABLE FEES1(
	SNO NUMBER(3),
	AMOUNT NUMBER(3),
	FEESDATE DATE
);

INSERT INTO STUDENT1 VALUES(1,'HIREN','BCA');

INSERT INTO FEES1 VALUES(1,'5000','1-DEC-2019');

DECLARE
	VSNO STUDENT1.SNO%TYPE;
	VNAME STUDENT1.NAME%TYPE;
	VCOURSE STUDENT1.COURSE%TYPE;
	
	VSNO
BEGIN

END;
/