CREATE TABLE TEAM(
	TNO NUMBER(3) CONSTRAINTS PKTNO PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE PLAYERS1(
	PNO NUMBER(3) NOT NULL,
	PNAME VARCHAR2(25),
	AGE NUMBER(3),
	TNO NUMBER(3) CONSTRAINTS FKTNO REFERENCES TEAM
);


DECLARE
	CURSOR TEAMPLAYERS IS
	SELECT T.TNO,T.NAME,P.PNO,P.NAME,P.AGE
	FROM TEAM T, PLAYERS P 
	WHERE T.TNO=P.TNO;
	P TEAMPLAYERS%ROWTYPE;
	LTNO NUMBER;
BEGIN
	OPEN TEAMPLAYERS;
	FETCH TEAMPLAYERS INTO TEAMPLAYERSROW;
	DBMS_OUTPUT.PUT_LINE(T.TNO || T.NAME);
	LTNO:=P.TNO;
	LOOP
		DBMS_OUTPUT.PUT_LINE(P.PNO||''||P.NAME||''||P.AGE);
		FETCH TEAMPLAYERS INTO TEAMPLAYERSROW;
		EXIT WHEN TEAMPLAYERS%NOTFOUND;
		IF LTNO <> TEAMPLAYERSROW.TNO THEN
			DBMS_OUTPUT.PUT_LINE('');
			LTNO:= TEAMPLAYERSROW.TNO;
		END IF;
	END LOOP;
END;
/